export const GET_INGREDIENTS = 'GET_INGREDIENTS'
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED'
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS'
export const REORDER_INGREDIENTS = 'REORDER_INGREDIENTS'

export const ACTIVE_TAB = 'ACTIVE_TAB'

export const GET_ODDER_NUMBER = 'GET_ODDER_NUMBER'
export const GET_ODDER_NUMBER_FAILED = 'GET_ODDER_NUMBER_FAILED'
export const GET_ODDER_NUMBER_SUCCESS = 'GET_ODDER_NUMBER_SUCCESS'

export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const DEL_INGREDIENT = 'DEL_INGREDIENT'

export const ADD_TO_CONSTRUCTOR = 'ADD_TO_CONSTRUCTOR'
export const DEL_FROM_CONSTRUCTOR = 'DEL_FROM_CONSTRUCTOR'

export const SET_UNIQUE_KEY = 'SET_UNIQUE_KEY'

export const SHOW_LOADER = 'SHOW_LOADER'