export const GET_INGREDIENTS = 'GET_INGREDIENTS'
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED'
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS'
export const REORDER_INGREDIENTS = 'REORDER_INGREDIENTS'

export const ACTIVE_TAB = 'ACTIVE_TAB'

export const GET_ODDER_NUMBER = 'GET_ODDER_NUMBER'
export const GET_ODDER_NUMBER_FAILED = 'GET_ODDER_NUMBER_FAILED'
export const GET_ODDER_NUMBER_SUCCESS = 'GET_ODDER_NUMBER_SUCCESS'

export const ADD_TO_CONSTRUCTOR = 'ADD_TO_CONSTRUCTOR'
export const DEL_FROM_CONSTRUCTOR = 'DEL_FROM_CONSTRUCTOR'
export const CLEAR_CONSTRUCTOR = 'CLEAR_CONSTRUCTOR'

export const SET_UNIQUE_KEY = 'SET_UNIQUE_KEY'

export const SHOW_LOADER = 'SHOW_LOADER'

export const GET_ORDER = 'GET_ORDER'
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const CLEAR_ORDER = 'CLEAR_ORDER'

export const GET_USER = 'GET_USER'
export const GET_USER_FAILED = 'GET_USER_FAILED'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'